### ISSUE TITLE
Create an environment file

### ISSUE THREAD

**Issue by tmcclintock** [tmcclintock/covariance_emulator#3]
A `conda` environment file will make our results reproducible by pinning our dependencies.

This should be sufficient:
```yaml
name: covemu
dependencies:
  - python>=3.6
  - twine
  - numpy
  - scipy
  - matplotlib
  - isort
  - black
  - flake8
  - pre-commit
  - pytest
  - coverage
  - george
```
