### ISSUE TITLE
Set up pre-commit

### ISSUE THREAD

**Issue by tmcclintock** [tmcclintock/covariance_emulator#4]
TODO items:

- [x] set up `.pre-commit-config.yaml`:
```yaml
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: isort
        require_serial: true
        types: [python]
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        entry: flake8
        require_serial: true
        types: [python]
```
- [x] set up `.isort.cfg`:
```cfg
[settings]
multi_line_output = 3
include_trailing_comma = True
indent='    '
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line_length = 88
```
- [x] set up `.flake8`:
```cfg
[flake8]
ignore = E501, W503, E203, E266, F403, F401, E402
max-line-length = 88
max-complexity = 18
select = B,C,E,F,W,T4,B9
```
- [x] set up `pyproject.toml`:
```toml
[tool.isort]
known_first_party = [
    "benchmarks",
    "docs",
    "tests",
]
profile = "black"
line_length = 120
force_sort_within_sections = "False"
order_by_type = "False"

[tool.black]
line-length = 82
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
```
- [ ] run pre-commit on all files
